m3-w8d3-session/FlyByNightBank.Web/Controllers/CalculatorsController.cs
using FlyByNightBank.Web.Models.Calculators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlyByNightBank.Web.Controllers
{

    public class CalculatorsController : Controller
    {                                
        // GET: Calculators/CompoundInterest
        public ActionResult CompoundInterest()
        {
            return View("CompoundInterest");
        }

        // GET: Calculators/CompoundInterestResult?Principal={0}&NumberOfYears={1}&InterestRate={2}
        public ActionResult CompoundInterestResult(double principal, int numberOfYears, double interestRate)
        {
            CompoundInterestModel model = new CompoundInterestModel()
            {
                Principal = principal,
                NumberOfYears = numberOfYears,
                InterestRate = interestRate
            };

            return View("CompoundInterestResult", model);
        }




        // GET: Calculators/TimeToPayOff
        public ActionResult TimeToPayOff()
        {
            return View("TimeToPayOff");
        }

        // GET: Calculators/TimeToPayOffResult?apr={0}&balance={1}&monthlyPayment={2}
        public ActionResult TimeToPayOffResult(CreditCardPayoffModel model)
        {
            return View("TimeToPayOffResult", model);
        }

        /*
        * Additional exercises to implement with students
        * if examples are needed.
        * Models already exist.
        */

        // GET: Calculators/MonthlyPayment
        public ActionResult MonthlyPayment()
        {
            throw new NotImplementedException();
        }

        // GET: Calculators/MonthlyPaymentResult
        public ActionResult MonthlyPaymentResult(MonthlyPaymentModel model)
        {
            throw new NotImplementedException();
        }


        

    }
}

m3-w8d3-session/FlyByNightBank.Web/Controllers/SurveyController.cs
using FlyByNightBank.Web.DAL;
using FlyByNightBank.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlyByNightBank.Web.Controllers
{
    public class SurveyController : Controller
    {
        //private SurveySqlDAL dal = new SurveySqlDAL(); //<-- private variable to hold the DAL
        private ISurveyDAL dal; //<-- private variable to hold the DAL

        public SurveyController(ISurveyDAL surveyDal) //<-- constructor to inject the surveyDAL
        {
            this.dal = surveyDal; //<-- assigns injected DAL to the private variable
        }

        // GET Survey/TakeSurvey
        [HttpGet]
        public ActionResult TakeSurvey()
        {
            // Instantiate the Survey model
            // Return a TakeSurvey view (and pass in the model)

            Survey model = new Survey();
            return View("TakeSurvey", model);
        }

        // POST: Survey/TakeSurvey
        [HttpPost] //<-- this is a POST METHOD ONLY
        public ActionResult TakeSurvey(Survey completedSurvey)
        {
            // Give completed survey to a dal
            // Return the SurveyResult view

            dal.SaveSurvey(completedSurvey);
            //return View("SurveyResult");
            return RedirectToAction("SurveyResult");
        }

        // GET: /Survey/SurveyResult
        public ActionResult SurveyResult()
        {
            return View("SurveyResult");
        }

        
    }
}

m3-w8d3-session/FlyByNightBank.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Fly By Night Bank - @ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/stylesheet.css" />
</head>
<body>
    <header>
        <img src="~/Content/img/flybynightlogo.png" alt="Fly By Night Bank" />
        <p>At Fly By Night, we treat your money as if it's our own.</p>
    </header>
    <nav>
        <ul>
            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
            <li><a href="#">Why Fly By Night</a></li>
            <li>@Html.ActionLink("Compound Interest Calculator", "CompoundInterest", "Calculators")</li>
            <li>@Html.ActionLink("Credit Card Payoff Calculator", "TimeToPayOff", "Calculators")</li>
            <li>@Html.ActionLink("Appreciation Survey", "Index", "Survey")</li>

            <li style="float: right;">
                @if (Session["visitor_zipcode"] == null)
                {
                    <form action="@Url.Action("ViewRates", "Home")" method="get">
                        <input type="text" placeholder="enter zip code" name="zipcode" />
                        <button>Get Rates</button>
                    </form>
                }
                else
                {
                    @*@Html.ActionLink("Rates for " + Session["visitor_zipcode"], "ViewRates", "Home")*@
                    <a href="@Url.Action("ViewRates", "Home")">Rates for @Session["visitor_zipcode"]</a>
                }
            </li>
        </ul>
    </nav>

    <section id="main">

        @RenderBody()

    </section>
    <footer>
        Fly By Night Bank | Varying Locations | sales@flybynightbank.com
    </footer>
</body>
</html>