m3-w7d5-layout-pages/SpaceCats.Web/Models/SpaceCat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SpaceCats.Web.Models
{
    public class SpaceCat
    {
        public string Name { get; set; }
        public string HomePlanet { get; set; }
        public string ImageUrl { get; set; }
        public string Id { get; set; }
        public string Keywords { get; set; }
    }
}

m3-w7d5-layout-pages/SpaceCats.Web/Controllers/SpaceCatsController.cs
using SpaceCats.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpaceCats.Web.Controllers
{
    public class SpaceCatsController : Controller
    {
        // GET: SpaceCats
        public ActionResult Index()
        {
            //normally we go to the DAL for this
            List<SpaceCat> cats = GetAllSpaceCats();
            return View("Index", cats); //<-- Index is the name of Index.cshtml
        }

        public ActionResult Detail(string id = "")
        {
            SpaceCat cat = GetSpaceCat(id);

            if (cat == null)
            {
                return HttpNotFound();
            }



            return View("Detail", cat);
        }





        // THESE WOULD NORMALLY GO INTO A SpaceCatDAL
        private SpaceCat GetSpaceCat(string id)
        {            
            List<SpaceCat> allSpaceCats = GetAllSpaceCats();

            foreach(var cat in allSpaceCats)
            {
                if(id.ToLower() == cat.Id)
                {
                    return cat; //<-- this cat has the id we need
                }
            }

            return null; //<-- we didn't find the cat with the id we wanted
        }


        private List<SpaceCat> GetAllSpaceCats()
        {
            List<SpaceCat> list = new List<SpaceCat>();
            SpaceCat cat1 = new SpaceCat();
            cat1.Name = "Felix";
            cat1.HomePlanet = "Mars";
            cat1.ImageUrl = "cat_1.jpg";
            cat1.Id = "felix";

            SpaceCat cat2 = new SpaceCat();
            cat2.Name = "Elon Meowsk";
            cat2.HomePlanet = "Earth";
            cat2.ImageUrl = "cat_2.jpg";
            cat2.Id = "elon-meowsk";

            SpaceCat cat3 = new SpaceCat();
            cat3.Name = "John Real Quick";
            cat3.HomePlanet = "Saturn";
            cat3.ImageUrl = "cat_3.jpg";
            cat3.Id = "john-real-quick";

            SpaceCat cat4 = new SpaceCat();
            cat4.Name = "Bill Purray";
            cat4.HomePlanet = "Venus";
            cat4.ImageUrl = "cat_4.png";
            cat4.Id = "bill-purray";
            
            list.Add(cat1);
            list.Add(cat2);
            list.Add(cat3);
            list.Add(cat4);

            return list;
        }


    }
}

m3-w7d5-layout-pages/SpaceCats.Web/Views/SpaceCats/Detail.cshtml
@using SpaceCats.Web.Models;
@model SpaceCat

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    
}

<h2>@Model.Name</h2>
<p>From: @Model.HomePlanet</p>
<img src="@Url.Content("~/Content/img/" + Model.ImageUrl)" />

m3-w7d5-layout-pages/SpaceCats.Web/Views/SpaceCats/Index.cshtml
@using SpaceCats.Web.Models;
@model List<SpaceCat>

@{
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    ViewBag.PageTitle = "Space Cat Directory";
    ViewBag.Keywords = "spacecats directory home-planets";
}


<p>There are currently @Model.Count known spacecats</p>

<table id="space-cat-directory">

    @*
        Dictionary<string, List<SpaceCat>> cats = new Dictionary<string, List<SpaceCat>>();
        var cats = new Dictionary<string, List<SpaceCat>>();
    *@

    @foreach (var cat in Model)
    {

        <tr>
            <td><a href="@Url.Action("Detail","SpaceCats", new { id = cat.Id})">
                    <img src="@Url.Content("~/Content/img/" + cat.ImageUrl)" />
                </a>
            </td>
            @*<td><img src="~/Content/img/@cat.ImageUrl" /></td>*@
            <td><a href="@Url.Action("Detail","SpaceCats", new { id = cat.Id})">@cat.Name</a></td>
            <td>@cat.HomePlanet</td>
        </tr>
    }

</table>